name: ProtectYourCastle
version: '1.2-SNAPSHOT'
main: fr.tt54.protectYourCastle.ProtectYourCastleMain
api-version: '1.20'
commands:
  castle:
    description: Commande de base
  drawbridge:
    description: Ouvre le pont-levis
    aliases: [db, pontlevis]
